package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.BooleanSupplier;
import java.util.function.Supplier;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandPS5Controller;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.commands.ShooterCmd;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.LimelightHelpers.LimelightTarget_Detector;
import frc.robot.subsystems.LimelightHelpers.PoseEstimate;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    public int checkcase = 0;
    public boolean wonAuto;
    double LensHeight = 13;
    double goalHeight= 2.955;
    double offsetAngleVertical;
    double distance;
    double tx,ty;
    boolean DetectedFuel;
    Command followCommand = null;
    private Rotation2d overrideRot;
    public Command pathfindingCommand;
    public boolean pathDone;
    //ShooterCalc shooterCalc;
    public boolean LimSeed = false;
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    public double calcdist;
    LimelightHelpers.PoseEstimate mt2 = new PoseEstimate();
    LimelightHelpers.PoseEstimate lim2mt2 = new PoseEstimate();
    boolean rejectUpdate;
    boolean rejectUpdate2;
    public double ReqRot;
    public double FinalError;
    public final double HubX= 11.935;
    public final double HubY= 4.024;
    private final double BumpX1 = 14.2;
    private final double BumpX2 = 10.4;
    private final double BumpY1 = 4.80;
    private final double BumpY2 = 6.120;
    public double Rot45;
    public double LastRot45 = 0;
    public double Error45;
    public double xOdo;
    public double yOdo;
    public double rot;
    public double LastReqRot = 0;
    public double Heading;
    public double Error;
    private CommandPS5Controller User1 = new CommandPS5Controller(0);
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond);
    private boolean autoRunning = false;
    private boolean visionEnabled = true;
    private double autoStartTime = 0;
    

    private final Field2d field = new Field2d();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {

        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }


    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide cyonstants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configureAutoBuilder();
    }
 

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                    () -> getState().Pose, // Supplier of current robot pose
                    this::resetPose, // Consumer for seeding pose against auto
                    () -> getState().Speeds,
                     // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                            m_pathApplyRobotSpeeds.withSpeeds(speeds)
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            // PID constants for translation
                            new PIDConstants(5, 0, 0),
                            // PID constants for rotation
                            new PIDConstants(5, 0, 0)),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the
                    // case
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Blue,
                    this // Subsystem for requirements
                    
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
                    ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }
   
    

    @Override
    public void periodic() {
        if (!BumperPos()){
            Rot45=-User1.getRightX() * MaxAngularRate * 0.6;
        }
        calcdist = Math.sqrt(Math.pow((HubY-yOdo),2) + Math.pow((HubX-xOdo),2));
                // if (getState().Pose.getRotation().getDegrees()>0){
                //     Heading = getState().Pose.getRotation().getDegrees();
                // }else {
                //     Heading = 360 - Math.abs(getState().Pose.getRotation().getDegrees());
                // }
                Heading = GetLimHeading();
                //Heading = getState().Pose.getRotation().getDegrees();
                xOdo = getState().Pose.getX();
                yOdo = getState().Pose.getY();
                double Error135 = 120-Heading;
                double Error_45 = -30-Heading;
                double Error_135 = -125-Heading;
                Error45 = 30-Heading;
                if (Error45>0){
                Error45= (Error45+180)%360-180;
                }
                else {
                    Error45= (Error45-180)%360+180;
                }
                if (Error135>0){
                Error135= (Error135+180)%360-180;
                }
                else {
                    Error135= (Error135-180)%360+180;
                }
                if (Error_45>0){
                Error_45= (Error_45+180)%360-180;
                }
                else {
                    Error_45= (Error_45-180)%360+180;
                }
                if (Error_135>0){
                Error_135= (Error_135+180)%360-180;
                }
                else {
                    Error_135= (Error_135-180)%360+180;
                }
                if (Math.abs(Error45)<=Math.abs(Error135) && Math.abs(Error45)<=Math.abs(Error_45)&& Math.abs(Error45)<=Math.abs(Error_135)){
                    
                    FinalError=Error45;
                }
                if (Math.abs(Error135)<=Math.abs(Error45) && Math.abs(Error135)<=Math.abs(Error_45)&& Math.abs(Error135)<=Math.abs(Error_135)){
                    FinalError=Error135;
                }
                if (Math.abs(Error_45)<=Math.abs(Error135) && Math.abs(Error_45)<=Math.abs(Error45)&& Math.abs(Error_45)<=Math.abs(Error_135)){
                    FinalError=Error_45;
                }
                if (Math.abs(Error_135)<=Math.abs(Error135) && Math.abs(Error_135)<=Math.abs(Error_45)&& Math.abs(Error_135)<=Math.abs(Error45)){
                    FinalError=Error_135;
                }
                if (FinalError>0){
                FinalError= (FinalError+180)%360-180;
                }
                else {
                    FinalError= (FinalError-180)%360+180;
                }
                ReqRot = Math.toDegrees(Math.atan2((HubY-yOdo), (HubX- xOdo)));
                Error = (ReqRot-Heading);
                if (ReqRot>0){
                    Error = (Error + 180) % 360 - 180;
                }
                else{
                    Error = (Error - 180) % 360 + 180;
                }

                if ((Math.abs(Error)>1)){         
                rot= (0.08*Error)+(0.0015*((Error-LastReqRot)/0.02));
                LastReqRot = Error;
                rot = Math.max(-1, Math.min(rot, 1));}
                else{
                    rot=0;
                }

                // if (Math.abs(Error)>180){
                //     boolean 
                // }

                
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        
        LimelightHelpers.setPipelineIndex("limelight-l",1);
        // LimelightHelpers.setPipelineIndex("limelight-ll", 0);
         LimelightHelpers.setPipelineIndex("limelight-ll", 4);
          if (!LimSeed){
            LimelightHelpers.SetIMUMode("limelight-l", 4);
            LimelightHelpers.SetIMUMode("limelight-ll", 4);
            LimelightHelpers.SetRobotOrientation("limelight-ll", GetLimHeading(), 0,0, 0, 0, 0);
        LimelightHelpers.SetRobotOrientation("limelight-l", GetLimHeading(), 0,0,0,0,0);

            //imelightHelpers.SetRobotOrientation("limelight-ll", Lime);
            //LimelightHelpers.SetRobo  tOrientation("limelight-l", getState().Pose.getRotation().getDegrees(), 0,0,0,0,0);
        }
        else {
            LimelightHelpers.SetRobotOrientation("limelight-ll", GetHeading(), 0,0, 0, 0, 0);
            LimelightHelpers.SetRobotOrientation("limelight-l", GetHeading(), 0,0,0,0,0);
            LimelightHelpers.SetIMUMode("limelight-ll", 1);
            LimelightHelpers.SetIMUMode("limelight-l", 1);
        }
        // LimelightHelpers.SetIMUAssistAlpha("limelight-l", 0.001);
        //LimelightHelpers.SetIMUMode("limelight-l", 0);
        //LimelightHelpers.SetIMUMode("limelight-ll", 0);
        // LimelightHelpers.setPipelineIndex("limelight-ll",0);
        // LimelightHelpers.SetIMUAssistAlpha("limelight-ll", 0.001);
        
         
        
        //LimelightHelpers.setLimelightNTDoubleArray("null", null, null);
        //LimelightHelpers.SetRobotOrientation("limelight-ll", getState().Pose.getRotation().getDegrees(), 0,0, 0, 0, 0);
        //LimelightHelpers.SetRobotOrientation("limelight-l", getState().Pose.getRotation().getDegrees(), 0,0,0,0,0);

        //LimelightHelpers.SetRobotOrientation("limelight-ll", getState().Pose.getRotation().getDegrees(), 0,0,0,0,0);

        //lim2mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-ll");
        mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-l");
        LimelightTarget_Detector limelightTarget_Detector = new LimelightTarget_Detector();
        LimelightHelpers.LimelightResults limelightResults = LimelightHelpers.getLatestResults("limelight-ll");
        LimelightHelpers.LimelightTarget_Detector[] detections = limelightResults.targets_Detector;
        for (LimelightHelpers.LimelightTarget_Detector detection : detections){
            if (detection.className.contentEquals("Fuel")){
                double[] BotSpace= LimelightHelpers.getTargetPose_RobotSpace("limelight-ll");
                ty = detection.ty;
                tx= detection.tx;
                offsetAngleVertical = detection.ty;
                double angleToGoalDefrees = Math.toRadians(ty);
                distance = (goalHeight-LensHeight)/Math.tan(angleToGoalDefrees);
                double Hdist = distance * Math.tan(Math.toRadians(tx));
                DetectedFuel = true;
            } else {
                DetectedFuel = false;

            }
        }
    
       // double data = LimelightHelpers.getIMUData("limelight-l").robotYaw;
        
        rejectUpdate = false;
        rejectUpdate2 = false;

        // ✅ 4. Normal rejection rules (only used BEFORE auto, or in teleop)
        if (mt2 == null || mt2.tagCount == 0)
            rejectUpdate = true;
        //  if (lim2mt2.tagCount == 0)
        //      rejectUpdate2 = true;


        if (Math.abs(getPigeon2().getAngularVelocityZDevice().getValueAsDouble()) > 720)
           rejectUpdate = true;
           //rejectUpdate2 = true;

        // //✅ 5. Apply MT2 once vision is enabled
        // if (!rejectUpdate) {
        //     // We trust X/Y but ignore theta
        //     setVisionMeasurementStdDevs(VecBuilder.fill(0.7, 0.7, 9999999));
        //     addVisionMeasurement(mt2.pose, mt2.timestampSeconds);
        // }
        // if (!rejectUpdate2) {
        //     // We trust X/Y but ignore theta
        //     // SmartDashboard.putString("runing", "lime2");
        //     // setVisionMeasurementStdDevs(VecBuilder.fill(0.7, 0.7, 9999999));
        //     // addVisionMeasurement(lim2mt2.pose, lim2mt2.timestampSeconds);
        // }
        // if (!rejectUpdate && !rejectUpdate2){
        //     setVisionMeasurementStdDevs(VecBuilder.fill(0.7, 0.7, 9999999));
        //     addVisionMeasurement(mt2.pose, mt2.timestampSeconds);
        // }
        // else {
        //     SmartDashboard.putString("not runing", "lime2");
        // }

        field.setRobotPose(getState().Pose);
        
        
        
        // ✅ 6. Dashboard
      ///  double x = getState().Pose.getX();
      //  x = mt2.pose.getX();
      //pathDone = false;
        SmartDashboard.putNumber("Vision X", (mt2 != null) ? mt2.pose.getX() : -99);
        SmartDashboard.putNumber("Vision Y", (mt2 != null) ? mt2.pose.getY() : -99);
        SmartDashboard.putNumber("Vision 2 X", (lim2mt2 != null) ? lim2mt2.pose.getX() : -99);
        SmartDashboard.putNumber("Vision 2 Y", (lim2mt2 != null) ? lim2mt2.pose.getY() : -99);
        SmartDashboard.putNumber("Robot X", getState().Pose.getX());
        SmartDashboard.putNumber("Robot Y", getState().Pose.getY());
        SmartDashboard.putNumber("Heading", GetHeading());
        SmartDashboard.putNumber("Velocity", getState().Speeds.vxMetersPerSecond);
        SmartDashboard.putNumber("Degrees Required",ReqRot);
        SmartDashboard.putBoolean("Is in Zone", BumperPos());
        SmartDashboard.putNumber("Error",Error);
        SmartDashboard.putNumber("ErrorFor45", FinalError);
        SmartDashboard.putNumber("Dist",calcdist);
        SmartDashboard.putNumber("LimelightTags", lim2mt2.tagCount);
        SmartDashboard.putBoolean("Lim2mt2", rejectUpdate2);
        SmartDashboard.putNumber("LimelightYaw",GetLimHeading());
        SmartDashboard.putBoolean("LimelightSeeding", LimSeed);
        SmartDashboard.putBoolean("Reject Update Lim1", rejectUpdate);
        SmartDashboard.putBoolean("Reject Update Lim2", rejectUpdate2);
        SmartDashboard.putBoolean("PathDone", pathDone);
        SmartDashboard.putBoolean("DetectedFuel", DetectedFuel);
        SmartDashboard.putNumber("DetectedFuel Tx", tx);
        SmartDashboard.putNumber("DetectedFuelTy", ty);
        SmartDashboard.putNumber("DistanceFromFuel", distance);
        SmartDashboard.putBoolean("Won Auto Or Not", wonAuto);
        SmartDashboard.putNumber("CheckCase", checkcase);

    
        
        //SmartDashboard.putData("null", field);
        //  SmartDashboard.putNumber("Best Velocity", shooterCalc.bestVelocity);
        //         SmartDashboard.putNumber("Best Angle", shooterCalc.bestAngle);
        //         SmartDashboard.putNumber("Best RPM", shooterCalc.bestVelocity*60/Math.PI*4);

        

        // ✅ Operator Perspective logic
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }
    public double BotHeading()  {
        return getState().Pose.getRotation().getDegrees();
    }
    public boolean AutoAllign(){
          if ((Math.abs(Error)>1)){         
                rot= (0.08*Error)+(0.0015*((Error-LastReqRot)/0.02));
                LastReqRot = Error;
                rot = Math.max(-0.6, Math.min(rot, 0.6));
                return true;
            }
            else {
                return false;
            }
                    
    }
    public boolean BumperPos(){
    //private final double BumpX1 = 14.2;
    //private final double BumpX2 = 11.294;
    //private final double BumpY1 = 4.970;
    //private final double BumpY2 = 6.120;
        if (xOdo<=BumpX1 && xOdo>=BumpX2 && yOdo>= BumpY1 && yOdo<=BumpY2){
            SmartDashboard.putString("Is ", "in Bumper Zone");
            Rot45 = (0.25*FinalError)+(0.0015*((FinalError-LastRot45)/0.02));
            LastRot45 = FinalError;
            Rot45 = Math.max(-1,Math.min(Rot45,1));
            return true;
        }
        else {
            return false;
        }
    }
    public Command pathFind(double x, double y, double Deg, BooleanSupplier override){
        PathConstraints constraints = new PathConstraints(1,1, Math.toRadians(500), Math.toRadians(600));
        pathDone = true;
        pathfindingCommand = AutoBuilder.pathfindToPose(new Pose2d(x,y, Rotation2d.fromDegrees(Deg)), constraints, 0);
        // Pathfinding.setGoalPosition(new Translation2d(x,y));
        // PathPlannerPath generatePath = Pathfinding.getCurrentPath(constraints, new GoalEndState(0.0, Rotation2d.fromDegrees(Deg)));
        // return Commands.waitUntil(()->Pathfinding.isNewPathAvailable()).andThen(
        //     Commands.runOnce(()->{
        //     generatePath = Pathfinding.getCurrentPath(constraints, new GoalEndState(0.0, Rotation2d.fromDegrees(Deg)));
        //     })
        return pathfindingCommand;
    }
     public Command CancelCommand(){
        pathfindingCommand = null;
        return pathfindingCommand;
    }
    public void AutoWon(){
        if (checkcase==0){
        wonAuto = true;
        checkcase++;
        }
        else {

        }
    }
     public void AutoLost(){
        if (checkcase==0){
        wonAuto = false;
        checkcase++;
        }
        else {

        }
    }
    
   
    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }
    public double getXPose(){
        return getState().Pose.getX();
    }
    public double getYPose(){
        return getState().Pose.getY();
    }
    public double GetHeading(){
        return getState().Pose.getRotation().getDegrees();
    }
    public Pose2d GetPose(){
        return getState().Pose;
    }

    public double GetLimHeading(){
        if (rejectUpdate && !rejectUpdate2)
        return LimelightHelpers.getIMUData("limelight-ll").robotYaw;
        else if (rejectUpdate2 && !rejectUpdate)
        return LimelightHelpers.getIMUData("limelight-l").robotYaw;
        else if (!rejectUpdate2 && !rejectUpdate)
        return LimelightHelpers.getIMUData("limelight-l").robotYaw;
        else 
        return LimelightHelpers.getIMUData("limelight-l").robotYaw;        

    }
    public void SetNSeed(){
        LimSeed = true;
    }
    public void rotOverride(double deg){
        overrideRot  = Rotation2d.fromDegrees(deg);
    }
     public void clearOverride(double deg){
        overrideRot  = null;
    }
    public double GetDistFromHub(){
        return calcdist;
    }
   
    
    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }
   


    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void AimingWithDistance(ShooterCmd shoot){

         calcdist = Math.sqrt(Math.pow((HubY-yOdo),2) + Math.pow((HubX-xOdo),2));
        //InterpolatingTreeMap table = new InterpolatingTreeMap<>(null, getKinematics());

    }
}
